version: '3.4'

services:
  neo4jworkerindotnet:
    image: ${DOCKER_REGISTRY-}neo4jworkerindotnet
    build:
      context: .
      dockerfile: Neo4jWorkerInDotNet/Dockerfile

  graphdb:
    image: neo4j
    ports:
    - 7474:7474
    - 7687:7687
    environment:
    - NEO4J_AUTH=neo4j/password


