version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    depends_on:
    - graph

  graph:
    image: neo4j
    ports:
    - 7474:4747
    - 7687:7687
    environment:
    - NEO4J_AUTH=neo4j/password
